controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: finger_joint
    use_effort_interface: true
    use_speed_interface: true
    max_velocity: 0.1  # Set the maximum velocity here

robotiq_activation_controller:
  ros__parameters:
    default: true
